on:
  release:
    types:
      - published

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          zip -r sdk-csharp.zip src/*

      - uses: actions/upload-artifact@v2
        with:
          name: sdk-csharp-${{ github.sha }}.zip
          path: sdk-csharp.zip

  tar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          tar -czvf sdk-csharp.tar.gz src/*

      - uses: actions/upload-artifact@v2
        with:
          name: sdk-csharp-${{ github.sha }}.tar.gz
          path: sdk-csharp.tar.gz

  release:
    needs:
      - zip
      - tar
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extension:
          - zip
          - tar.gz
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: sdk-csharp-${{ github.sha }}.${{ matrix.extension }}
          path: sdk-csharp

      - run: |
          cp CHANGELOG.md LICENSE README.md sdk-csharp/

      - name: Pack artifact (zip)
        if: startsWith(matrix.extension, 'zip')
        run: |
          zip -r sdk-csharp.zip sdk-csharp/*

      - name: Pack artifact (tar)
        if: startsWith(matrix.extension, 'tar')
        run: |
          tar -czvf sdk-csharp.tar.gz sdk-csharp/*

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          files: |
            sdk-csharp.${{ matrix.extension }}
